import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, ElementRef, NgZone, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';

type Mode='league'|'knockout'; type KnockoutView='matches'|'bracket'; type FinishType='spin'|'over'|'burst'|'xtreme';
interface Match{id:number;round:number;a:string|null;b:string|null;sa:number|null;sb:number|null;battleRound?:number} interface Standing{name:string;wins:number;losses:number;scored:number;against:number;points:number}
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./app.component.html',styleUrl:'./app.component.scss'})
export class AppComponent{
 @ViewChild('cameraPreview') cameraPreview?:ElementRef<HTMLVideoElement>;
 title='戰鬥陀螺挑戰賽';count=5;mode:Mode='league';knockoutView:KnockoutView='matches';names:string[]=[];players:string[]=[];matches:Match[]=[];started=false;error='';battleMatch:Match|null=null;battleRound=1;launchFails={a:0,b:0};countdownPlaying=false;recording=false;cameraReady=false;recordingUrl='';cameraError='';private countdownAudio?:HTMLAudioElement;private cameraStream?:MediaStream;private mediaRecorder?:MediaRecorder;private recordedChunks:Blob[]=[];private readonly storageKey='beybladeTournamentAngularV1';
 constructor(private zone:NgZone,private cdr:ChangeDetectorRef){this.resizeNames();this.restore()} resizeNames(){const n=Math.max(2,Math.min(64,Number(this.count)||2));this.count=n;this.names=Array.from({length:n},(_,i)=>this.names[i]??'')} trackByIndex(index:number){return index} setMode(mode:Mode){this.mode=mode} setKnockoutView(view:KnockoutView){this.knockoutView=view} demo(){const d=['小明','小華','阿哲','小宇','小凱','小杰','小安','小翔'];this.names=this.names.map((_,i)=>d[i]??`選手${i+1}`)}
 private shuffle<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a} start(){const p=this.names.map(x=>x.trim());if(p.some(x=>!x)){this.error='請輸入所有選手名稱';return}if(new Set(p).size!==p.length){this.error='選手名稱不可重複';return}this.error='';this.players=this.shuffle(p);this.matches=[];this.knockoutView='matches';this.mode==='league'?this.makeLeague():this.makeKnockout();this.started=true;this.save()}
 private makeLeague(){let id=0;const pool:Match[]=[];for(let i=0;i<this.players.length;i++)for(let j=i+1;j<this.players.length;j++)pool.push({id:id++,round:1,a:this.players[i],b:this.players[j],sa:null,sb:null,battleRound:1});this.matches=this.buildRestFriendlySchedule(pool).map((m,i)=>({...m,id:i}))} private buildRestFriendlySchedule(source:Match[]):Match[]{const remaining=this.shuffle(source),result:Match[]=[],lastPlayed=new Map<string,number>();while(remaining.length){const currentIndex=result.length;let bestGap=-1,candidates:number[]=[];for(let i=0;i<remaining.length;i++){const m=remaining[i],aLast=m.a?lastPlayed.get(m.a):-Infinity,bLast=m.b?lastPlayed.get(m.b):-Infinity,aGap=aLast===undefined?Infinity:currentIndex-aLast-1,bGap=bLast===undefined?Infinity:currentIndex-bLast-1,gap=Math.min(aGap,bGap);if(gap>bestGap){bestGap=gap;candidates=[i]}else if(gap===bestGap)candidates.push(i)}const pick=candidates[Math.floor(Math.random()*candidates.length)],[m]=remaining.splice(pick,1);result.push(m);if(m.a)lastPlayed.set(m.a,currentIndex);if(m.b)lastPlayed.set(m.b,currentIndex)}return result}
 private makeKnockout(){const size=this.nextPow2(this.players.length),seeded:(string|null)[]=[...this.players];while(seeded.length<size)seeded.push(null);const draw=this.shuffle(seeded);for(let i=0;i<size;i+=2)this.matches.push({id:this.matches.length,round:1,a:draw[i],b:draw[i+1],sa:null,sb:null,battleRound:1});this.buildNextRounds()} private nextPow2(n:number){let x=1;while(x<n)x*=2;return x}
 openBattle(m:Match){if(!m.a||!m.b)return;this.battleMatch=m;this.battleRound=m.battleRound??1;this.resetLaunchFails();this.cameraError=''} closeBattle(){this.countdownAudio?.pause();this.countdownPlaying=false;this.stopRecording();this.stopCamera();if(this.battleMatch){this.battleMatch.battleRound=this.battleRound;this.save()}this.battleMatch=null;this.resetLaunchFails()} battlePoints(side:'a'|'b'){if(!this.battleMatch)return 0;return side==='a'?(this.battleMatch.sa??0):(this.battleMatch.sb??0)} get battleFinished(){return!!this.battleMatch&&((this.battleMatch.sa??0)>=4||(this.battleMatch.sb??0)>=4)}
 private async ensureCamera(){if(this.cameraStream)return true;if(!navigator.mediaDevices?.getUserMedia){this.cameraError='此瀏覽器不支援網頁相機錄影';return false}try{this.cameraError='';this.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:true});this.cameraReady=true;setTimeout(()=>{const video=this.cameraPreview?.nativeElement;if(video&&this.cameraStream){video.srcObject=this.cameraStream;video.play().catch(()=>{})}},0);return true}catch(e){console.error(e);this.cameraError='無法開啟相機／麥克風，請確認瀏覽器權限';return false}}
 private async startRecording(){if(this.recording)return true;if(!(await this.ensureCamera())||!this.cameraStream)return false;if(typeof MediaRecorder==='undefined'){this.cameraError='此瀏覽器不支援網頁錄影';return false}try{if(this.recordingUrl){URL.revokeObjectURL(this.recordingUrl);this.recordingUrl=''}this.recordedChunks=[];const types=['video/mp4;codecs=h264,aac','video/mp4','video/webm;codecs=vp9,opus','video/webm'],mimeType=types.find(t=>MediaRecorder.isTypeSupported(t));this.mediaRecorder=mimeType?new MediaRecorder(this.cameraStream,{mimeType}):new MediaRecorder(this.cameraStream);this.mediaRecorder.ondataavailable=e=>{if(e.data.size)this.recordedChunks.push(e.data)};this.mediaRecorder.onstop=()=>this.zone.run(()=>{if(!this.recordedChunks.length)return;const type=this.mediaRecorder?.mimeType||this.recordedChunks[0].type||'video/webm';this.recordingUrl=URL.createObjectURL(new Blob(this.recordedChunks,{type}));this.cdr.detectChanges()});this.mediaRecorder.start(250);this.recording=true;return true}catch(e){console.error(e);this.cameraError='錄影啟動失敗';return false}}
 stopRecording(){if(this.mediaRecorder&&this.mediaRecorder.state!=='inactive'){try{this.mediaRecorder.requestData()}catch{}this.mediaRecorder.stop()}this.recording=false;this.cdr.detectChanges()} private stopCamera(){this.cameraStream?.getTracks().forEach(t=>t.stop());this.cameraStream=undefined;this.cameraReady=false} downloadRecording(){if(!this.recordingUrl)return;const a=document.createElement('a');a.href=this.recordingUrl;a.download=`beyblade-R${this.battleRound}-${Date.now()}.${this.mediaRecorder?.mimeType.includes('mp4')?'mp4':'webm'}`;a.click()}
 async playCountdown(){if(this.countdownPlaying||this.battleFinished||this.recording)return;await this.startRecording();try{this.countdownPlaying=true;if(!this.countdownAudio){const response=await fetch('assets/audio/321-go-shoot.mp3.b64');if(!response.ok)throw new Error('countdown audio not found');const base64=(await response.text()).trim(),binary=atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:'audio/mpeg'}));this.countdownAudio=new Audio(url);this.countdownAudio.preload='auto';this.countdownAudio.onended=()=>this.zone.run(()=>{this.countdownPlaying=false;this.cdr.detectChanges()});this.countdownAudio.onerror=()=>this.zone.run(()=>{this.countdownPlaying=false;this.cdr.detectChanges()})}this.countdownAudio.currentTime=0;await this.countdownAudio.play()}catch(e){console.error(e);this.countdownPlaying=false}}
 addBattleScore(side:'a'|'b',type:FinishType){if(!this.battleMatch||this.battleFinished)return;const add=this.finishPoints(type);if(side==='a')this.battleMatch.sa=(this.battleMatch.sa??0)+add;else this.battleMatch.sb=(this.battleMatch.sb??0)+add;this.stopRecording();const finished=this.battleFinished;if(!finished)this.battleRound++;this.battleMatch.battleRound=this.battleRound;this.resetLaunchFails();this.updateScore(this.battleMatch)}
 launchFail(side:'a'|'b'){if(!this.battleMatch||this.battleFinished)return;this.launchFails[side]++;this.stopRecording();if(this.launchFails[side]<2)return;const opponent=side==='a'?'b':'a';if(opponent==='a')this.battleMatch.sa=(this.battleMatch.sa??0)+1;else this.battleMatch.sb=(this.battleMatch.sb??0)+1;const finished=this.battleFinished;if(!finished)this.battleRound++;this.battleMatch.battleRound=this.battleRound;this.resetLaunchFails();this.updateScore(this.battleMatch)}
 drawBattle(){if(this.battleFinished)return;this.stopRecording()} private resetLaunchFails(){this.launchFails={a:0,b:0}} private finishPoints(type:FinishType){return type==='spin'?1:type==='xtreme'?3:2} resetBattle(){if(!this.battleMatch)return;this.stopRecording();this.battleMatch.sa=null;this.battleMatch.sb=null;this.battleRound=1;this.battleMatch.battleRound=1;this.resetLaunchFails();this.updateScore(this.battleMatch)}
 winner(m:Match):string|null|undefined{if(!m.a)return m.b;if(!m.b)return m.a;if(m.sa===null||m.sb===null||m.sa===m.sb)return undefined;return m.sa>m.sb?m.a:m.b} isWinner(m:Match,player:string|null){return!!player&&this.winner(m)===player} hasWinner(m:Match){return this.winner(m)!==undefined&&this.winner(m)!==null} updateScore(m:Match){m.sa=m.sa===null?null:Math.max(0,Number(m.sa));m.sb=m.sb===null?null:Math.max(0,Number(m.sb));m.battleRound=this.battleRound;if(this.mode==='knockout'){this.matches=this.matches.filter(x=>x.round<=m.round);this.buildNextRounds()}this.save()}
 private buildNextRounds(){const total=Math.log2(this.nextPow2(this.players.length));for(let r=1;r<total;r++){const prev=this.matches.filter(m=>m.round===r);if(!prev.length||!prev.every(m=>this.winner(m)!==undefined))break;if(this.matches.some(m=>m.round===r+1))continue;for(let i=0;i<prev.length;i+=2)this.matches.push({id:this.matches.length,round:r+1,a:this.winner(prev[i])??null,b:this.winner(prev[i+1])??null,sa:null,sb:null,battleRound:1})}}
 get standings():Standing[]{const s=this.players.map(name=>({name,wins:0,losses:0,scored:0,against:0,points:0}));for(const m of this.matches){if(m.sa===null||m.sb===null||!m.a||!m.b)continue;const a=s.find(x=>x.name===m.a)!,b=s.find(x=>x.name===m.b)!;a.scored+=m.sa;a.against+=m.sb;b.scored+=m.sb;b.against+=m.sa;if(m.sa>m.sb){a.wins++;b.losses++;a.points+=3}else if(m.sb>m.sa){b.wins++;a.losses++;b.points+=3}else{a.points++;b.points++}}return s.sort((a,b)=>b.points-a.points||b.wins-a.wins||(b.scored-b.against)-(a.scored-a.against)||b.scored-a.scored)} get rounds(){return Array.from({length:this.finalRound},(_,i)=>i+1)} roundMatches(r:number){return this.matches.filter(m=>m.round===r)} bracketSlotCount(r:number){return this.nextPow2(this.players.length)/Math.pow(2,r)} bracketMatches(r:number){const existing=this.roundMatches(r);return Array.from({length:this.bracketSlotCount(r)},(_,i)=>existing[i]??({id:-(r*100+i),round:r,a:null,b:null,sa:null,sb:null,battleRound:1} as Match))} expectedLabel(r:number,index:number,side:'a'|'b'){if(r===1)return'輪空';const prevIndex=index*2+(side==='b'?1:0);return`第 ${r-1} 輪第 ${prevIndex+1} 場勝者`} get finalRound(){return Math.log2(this.nextPow2(this.players.length))} get champion(){const f=this.matches.find(m=>m.round===this.finalRound);return f?this.winner(f):undefined} back(){this.started=false;this.closeBattle()} clear(){if(confirm('確定清除目前比賽紀錄？')){localStorage.removeItem(this.storageKey);location.reload()}} private save(){localStorage.setItem(this.storageKey,JSON.stringify({title:this.title,count:this.count,mode:this.mode,knockoutView:this.knockoutView,names:this.names,players:this.players,matches:this.matches,started:this.started}))} private restore(){try{const d=JSON.parse(localStorage.getItem(this.storageKey)||'null');if(!d)return;Object.assign(this,d);this.knockoutView=d.knockoutView??'matches'}catch{}}
}